In [1]:
"""
Live power breakdown

    "powerProduction" (in MW) represents the electricity produced in the zone, broken down by production type
    "powerConsumption" (in MW) represents the electricity consumed in the zone, after taking into account imports and exports, and broken down by production type.
    "powerExport" and "Power import" (in MW) represent the physical electricity flows at the zone border
    "renewablePercentage" and "fossilFreePercentage" refers to the % of the power consumption breakdown coming from renewables or fossil-free power plants (renewables and nuclear) It can either be queried by zone identifier or by geolocation.
"""
import json
import os
import pandas as pd
import requests
from datetime import datetime as dt
from dateutil.relativedelta import relativedelta
from dotenv import load_dotenv
pd.set_option('display.max_columns', 50)
load_dotenv()

api_key = os.getenv('ELECTRICITYMAPS_API')
endpoint = 'https://api.electricitymap.org/v3/power-breakdown/latest?'




header = {'auth-token': api_key}

In [15]:
zone_endpoint = 'https://api.electricitymap.org/v3/zones'
response = requests.get(zone_endpoint, header)
zone_data = response.json()

breakdown_df = pd.DataFrame()

for key, value in zone_data.items():
    query = 'zone='+key
    url = endpoint + query
    response = requests.get(url, header).json()
    if len(response) != 1:
        breakdown_df = pd.concat([breakdown_df, pd.DataFrame(response, index=[0])])

In [16]:

breakdown_df.head()

,zone,datetime,updatedAt,createdAt,powerConsumptionBreakdown,powerProductionBreakdown,powerImportBreakdown,powerExportBreakdown,fossilFreePercentage,renewablePercentage,powerConsumptionTotal,powerProductionTotal,powerImportTotal,powerExportTotal,isEstimated,estimationMethod
0,AE,2024-05-18T16:00:00.000Z,2024-05-18T15:48:55.303Z,2024-05-15T16:49:42.157Z,NaN,NaN,NaN,NaN,10,0,23642,23642,0,0,True,RECONSTRUCT_PRODUCTION_FROM_CONSUMPTION
0,AR,2024-05-18T16:00:00.000Z,2024-05-18T15:48:39.409Z,2024-05-15T16:50:08.661Z,NaN,NaN,NaN,NaN,47,38,17586,17527,59,0,True,TIME_SLICER_AVERAGE
0,AT,2024-05-18T16:00:00.000Z,2024-05-18T15:48:39.409Z,2024-05-15T16:49:18.161Z,NaN,NaN,NaN,NaN,99,99,7609,8600,186,1177,True,TIME_SLICER_AVERAGE
0,AU,2024-05-18T16:00:00.000Z,2024-05-18T15:48:55.303Z,2024-05-15T16:50:08.661Z,NaN,NaN,NaN,NaN,24,24,22947,23040,0,0,True,TIME_SLICER_AVERAGE
0,AU-NSW,2024-05-18T16:00:00.000Z,2024-05-18T15:48:55.303Z,2024-05-15T16:50:22.374Z,NaN,NaN,NaN,NaN,11,11,7356,7151,497,228,True,TIME_SLICER_AVERAGE

In [13]:
breakdown_df.shape

(225, 16)